version: '3'

x-defaults: &defaults
  image: sparanoid/almace-scaffolding:latest
  restart: always
  volumes:
    - ./_app/_pages/:/app/_app/_pages/
    - ./_app/_layouts/:/app/_app/_layouts/
    - ./_app/_includes/:/app/_app/_includes/
    - ./_app/_data/:/app/_app/_data/
    - ./_app/_posts/:/app/_app/_posts/
    - ./_config.yml:/app/_config.yml
    - ./_app/assets:/app/_app/assets
  ports:
    - "4321:4321"

services:
  amsf:
    <<: *defaults
    command: serve